CC=g++
CFLAGS=-std=c++11 -Wall -O2

##### BREAKTHROUGH
rand_player: mybt.h rand_player.cpp
	$(CC) $(CFLAGS) rand_player.cpp -o $@


##### BREAKTHROUGH
MCTSRP: mybt.h MCTSRP.cpp
	$(CC) $(CFLAGS) MCTSRP.cpp -o $@

